# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
steps:
- task: Maven@3
  displayName: Build docker image
  inputs:
    mavenPomFile: 'pom.xml'
    goals: 'spring-boot:build-image'
    publishJUnitResults: false
    jdkVersionOption: '1.11'
- task: Docker@2
  displayName: Push docker image
  inputs:
    containerRegistry: 'DockerHubConnection'
    repository: 'henrifola/blogsite'
    command: 'push'
    tags: 'latest'
- task: Bash@3
  displayName: 'Create docker password file'
  inputs:
    targetType: 'inline'
    script: 'echo $SECRET_PW > docker_pw.txt'
  env:
    SECRET_PW: $(docker_pw)
- task: CopyFiles@2
  displayName: Copy files to artifact directory
  inputs:
    Contents: |
      docker-compose.yml
      docker_pw.txt
    TargetFolder: '$(Build.ArtifactStagingDirectory)'
- task: PublishBuildArtifacts@1
  displayName: Publish artifact
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'